version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}

services:

  backend:
    build:
      context: ./myratingbud-backend
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./myratingbud-backend/:/app:z
    env_file:
      - ./myratingbud-backend/.envs/.local/.django
      - ./myratingbud-backend/.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    restart: unless-stopped

  postgres:
    image: postgres:12.3
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./myratingbud-backend/.envs/.local/.postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./myratingbud-frontend
      dockerfile: ../docker-compose/production/frontend/Dockerfile
    ports:
      - 80:5000
    volumes:
      - ./myratingbud-frontend:/app
      - /app/node_modules
    stdin_open: true
    restart: unless-stopped